/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.ayarlar.ActionAyarlari;
import gui.ayarlar.ButonAyarları;
import gui.ayarlar.IDuzenleyici;
import java.awt.Color;
import javax.swing.JButton;
/**
 *
 * @author Hakan
 */
public class StokEkleEkrani extends javax.swing.JFrame implements IDuzenleyici {

    private JButton JButton;

    /**
     * Creates new form StokEkleEkrani
     */
    public StokEkleEkrani() {
        initComponents();
        getEdits();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
     @Override
    public void getEdits() {
        this.setLocationRelativeTo(null);
        stokEklePanel.setFocusable(true);
        
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        stokEklePanel = new javax.swing.JPanel();
        stokAdıLabel = new javax.swing.JLabel();
        stokModelLabel = new javax.swing.JLabel();
        kayitIslemleriLabel = new javax.swing.JLabel();
        stokModeliLabel = new javax.swing.JLabel();
        stokTarihiLabel = new javax.swing.JLabel();
        stokKayitYapanLabel = new javax.swing.JLabel();
        stokAdıText = new javax.swing.JTextField();
        stokKaydıYapanText = new javax.swing.JTextField();
        stokTarihiText = new javax.swing.JTextField();
        stokModeliText = new javax.swing.JTextField();
        stokAdediText = new javax.swing.JTextField();
        cikisIkon = new javax.swing.JLabel();
        stokSilButon = new javax.swing.JButton();
        stokEkleButon = new javax.swing.JButton();
        stokGuncelleButon = new javax.swing.JButton();
        stokAdıLabel1 = new javax.swing.JLabel();
        fotoLabel = new javax.swing.JLabel();
        fotoEkleButon = new javax.swing.JButton();
        fotoSilButon = new javax.swing.JButton();
        stokKoduLabel = new javax.swing.JLabel();
        stokKoduText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STOK KAYIT İŞLEMLERİ");

        stokAdıLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        stokAdıLabel.setText("Stok Adı");

        stokModelLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        stokModelLabel.setText("Stok Adedi");

        kayitIslemleriLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kayitIslemleriLabel.setText("-Kayıt İşlemleri-");

        stokModeliLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        stokModeliLabel.setText("Stok Modeli");

        stokTarihiLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        stokTarihiLabel.setText("Stok Tarihi");

        stokKayitYapanLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        stokKayitYapanLabel.setText("Stok Kaydı Yapan");

        stokAdıText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokAdıTextActionPerformed(evt);
            }
        });

        stokKaydıYapanText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokKaydıYapanTextActionPerformed(evt);
            }
        });

        stokTarihiText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokTarihiTextActionPerformed(evt);
            }
        });

        stokModeliText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokModeliTextActionPerformed(evt);
            }
        });

        stokAdediText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokAdediTextActionPerformed(evt);
            }
        });

        cikisIkon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/İconlar/logoCikis.png"))); // NOI18N
        cikisIkon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cikisIkon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cikisIkonMouseClicked(evt);
            }
        });

        stokSilButon.setBackground(new java.awt.Color(255, 204, 255));
        stokSilButon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        stokSilButon.setText("Stok Sil");
        stokSilButon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stokSilButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stokSilButonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stokSilButonMouseExited(evt);
            }
        });

        stokEkleButon.setBackground(new java.awt.Color(204, 204, 255));
        stokEkleButon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        stokEkleButon.setText("Stok Ekle");
        stokEkleButon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stokEkleButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stokEkleButonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stokEkleButonMouseExited(evt);
            }
        });

        stokGuncelleButon.setBackground(new java.awt.Color(255, 255, 204));
        stokGuncelleButon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        stokGuncelleButon.setText("Stok Güncelle");
        stokGuncelleButon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stokGuncelleButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stokGuncelleButonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stokGuncelleButonMouseExited(evt);
            }
        });

        stokAdıLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        stokAdıLabel1.setText("-Fotoğraf Ekle-");

        fotoEkleButon.setBackground(new java.awt.Color(204, 255, 204));
        fotoEkleButon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fotoEkleButon.setText("Fotoğraf Ekle");
        fotoEkleButon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fotoEkleButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fotoEkleButonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fotoEkleButonMouseExited(evt);
            }
        });
        fotoEkleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fotoEkleButonActionPerformed(evt);
            }
        });

        fotoSilButon.setBackground(new java.awt.Color(153, 255, 153));
        fotoSilButon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fotoSilButon.setText("Fotoğraf Sil");
        fotoSilButon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fotoSilButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fotoSilButonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fotoSilButonMouseExited(evt);
            }
        });

        stokKoduLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        stokKoduLabel.setText("Stok Kodu");

        stokKoduText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokKoduTextActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Stok Kodu", "Stok Adı", "Stok Modeli", "Stok Adedi", "Stok Tarihi", "Kaydı Yapan", "Fotoğraf"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout stokEklePanelLayout = new javax.swing.GroupLayout(stokEklePanel);
        stokEklePanel.setLayout(stokEklePanelLayout);
        stokEklePanelLayout.setHorizontalGroup(
            stokEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stokEklePanelLayout.createSequentialGroup()
                .addGroup(stokEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stokEklePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cikisIkon))
                    .addGroup(stokEklePanelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(kayitIslemleriLabel))
                    .addGroup(stokEklePanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(stokEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(stokEklePanelLayout.createSequentialGroup()
                                .addGroup(stokEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(stokEklePanelLayout.createSequentialGroup()
                                        .addComponent(stokEkleButon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(stokSilButon)
                                        .addGap(18, 18, 18)
                                        .addComponent(stokGuncelleButon))
                                    .addGroup(stokEklePanelLayout.createSequentialGroup()
                                        .addGroup(stokEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(stokAdıLabel)
                                            .addComponent(stokModeliLabel)
                                            .addComponent(stokModelLabel)
                                            .addComponent(stokTarihiLabel)
                                            .addComponent(stokKayitYapanLabel)
                                            .addComponent(stokKoduLabel))
                                        .addGap(18, 18, 18)
                                        .addGroup(stokEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(stokKoduText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(stokAdıText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(stokModeliText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(stokAdediText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(stokTarihiText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(stokKaydıYapanText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(stokEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(stokEklePanelLayout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addGroup(stokEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(stokAdıLabel1)
                                            .addComponent(fotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(stokEklePanelLayout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(fotoEkleButon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fotoSilButon)))))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        stokEklePanelLayout.setVerticalGroup(
            stokEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stokEklePanelLayout.createSequentialGroup()
                .addGroup(stokEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stokEklePanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(cikisIkon, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(kayitIslemleriLabel)
                        .addGap(18, 18, 18)
                        .addGroup(stokEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(stokEklePanelLayout.createSequentialGroup()
                                .addComponent(stokKoduText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stokAdıText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stokModeliText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stokAdediText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stokTarihiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stokKaydıYapanText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(stokEklePanelLayout.createSequentialGroup()
                                .addComponent(stokKoduLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stokAdıLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stokModeliLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stokModelLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stokTarihiLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stokKayitYapanLabel)))
                        .addGap(32, 32, 32)
                        .addGroup(stokEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stokGuncelleButon)
                            .addComponent(stokSilButon)
                            .addComponent(stokEkleButon)
                            .addComponent(fotoEkleButon)
                            .addComponent(fotoSilButon)))
                    .addGroup(stokEklePanelLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(stokEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stokAdıLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stokEklePanelLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(fotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        stokEklePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {stokAdediText, stokAdıLabel, stokAdıText, stokKaydıYapanText, stokKayitYapanLabel, stokKoduLabel, stokKoduText, stokModelLabel, stokModeliLabel, stokModeliText, stokTarihiLabel, stokTarihiText});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stokEklePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stokEklePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void stokAdıTextActionPerformed(java.awt.event.ActionEvent evt) {                                            
       
    }                                           

    private void stokKaydıYapanTextActionPerformed(java.awt.event.ActionEvent evt) {                                                   
       
    }                                                  

    private void stokTarihiTextActionPerformed(java.awt.event.ActionEvent evt) {                                               
       
    }                                              

    private void stokModeliTextActionPerformed(java.awt.event.ActionEvent evt) {                                               
       
    }                                              

    private void stokAdediTextActionPerformed(java.awt.event.ActionEvent evt) {                                              
       
    }                                             

    private void fotoEkleButonActionPerformed(java.awt.event.ActionEvent evt) {                                              
       
    }                                             

    private void stokKoduTextActionPerformed(java.awt.event.ActionEvent evt) {                                             
       
    }                                            

    private void stokEkleButonMouseEntered(java.awt.event.MouseEvent evt) {                                           
         ButonAyarları.setBgFg(stokEkleButon, Color.BLACK, Color.WHITE);
    }                                          

    private void stokEkleButonMouseExited(java.awt.event.MouseEvent evt) {                                          
        ButonAyarları.setOriginalBgFg(stokEkleButon);
    }                                         

    private void stokSilButonMouseEntered(java.awt.event.MouseEvent evt) {                                          
        ButonAyarları.setBgFg(stokSilButon, Color.BLACK, Color.WHITE);
    }                                         

    private void stokSilButonMouseExited(java.awt.event.MouseEvent evt) {                                         
          ButonAyarları.setOriginalBgFg(stokSilButon);
    }                                        

    private void stokGuncelleButonMouseEntered(java.awt.event.MouseEvent evt) {                                               
          ButonAyarları.setBgFg(stokGuncelleButon, Color.BLACK, Color.WHITE);
    }                                              

    private void stokGuncelleButonMouseExited(java.awt.event.MouseEvent evt) {                                              
        ButonAyarları.setOriginalBgFg(stokGuncelleButon);
    }                                             

    private void fotoEkleButonMouseEntered(java.awt.event.MouseEvent evt) {                                           
       ButonAyarları.setBgFg(fotoEkleButon, Color.BLACK, Color.WHITE);
    }                                          

    private void fotoEkleButonMouseExited(java.awt.event.MouseEvent evt) {                                          
        ButonAyarları.setOriginalBgFg(fotoEkleButon);
    }                                         

    private void fotoSilButonMouseEntered(java.awt.event.MouseEvent evt) {                                          
        ButonAyarları.setBgFg(fotoSilButon, Color.BLACK, Color.WHITE);
    }                                         

    private void fotoSilButonMouseExited(java.awt.event.MouseEvent evt) {                                         
        ButonAyarları.setOriginalBgFg(fotoSilButon);
    }                                        

    private void cikisIkonMouseClicked(java.awt.event.MouseEvent evt) {                                       
         ActionAyarlari.SetVisible(this, new KullaniciEkrani());
    }                                      

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StokEkleEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StokEkleEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StokEkleEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StokEkleEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StokEkleEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel cikisIkon;
    private javax.swing.JButton fotoEkleButon;
    private javax.swing.JLabel fotoLabel;
    private javax.swing.JButton fotoSilButon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel kayitIslemleriLabel;
    private javax.swing.JTextField stokAdediText;
    private javax.swing.JLabel stokAdıLabel;
    private javax.swing.JLabel stokAdıLabel1;
    private javax.swing.JTextField stokAdıText;
    private javax.swing.JButton stokEkleButon;
    private javax.swing.JPanel stokEklePanel;
    private javax.swing.JButton stokGuncelleButon;
    private javax.swing.JTextField stokKaydıYapanText;
    private javax.swing.JLabel stokKayitYapanLabel;
    private javax.swing.JLabel stokKoduLabel;
    private javax.swing.JTextField stokKoduText;
    private javax.swing.JLabel stokModelLabel;
    private javax.swing.JLabel stokModeliLabel;
    private javax.swing.JTextField stokModeliText;
    private javax.swing.JButton stokSilButon;
    private javax.swing.JLabel stokTarihiLabel;
    private javax.swing.JTextField stokTarihiText;
    // End of variables declaration                   

   
}